version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd livy-builder/0.4
      - docker build --cache-from public.ecr.aws/f1n8f8j1/livy-builder:0.4 -t public.ecr.aws/f1n8f8j1/livy-builder:0.4 .
      - docker push --all-tags public.ecr.aws/f1n8f8j1/livy-builder
      - cd ../..
      - cd spark/3.2.0_2.12-hadoop_3.3.1_cloud
      - docker build --cache-from public.ecr.aws/f1n8f8j1/spark:3.2.0_2.12-hadoop_3.3.1_cloud -t public.ecr.aws/f1n8f8j1/spark:3.2.0_2.12-hadoop_3.3.1_cloud .
      - docker push --all-tags public.ecr.aws/f1n8f8j1/spark
      - cd ../..
      - cd livy-spark/0.8.0-incubating-spark_3.2.0_2.12-hadoop_3.3.1
      - docker build --cache-from public.ecr.aws/f1n8f8j1/livy-spark:0.8.0-incubating-spark_3.2.0_2.12-hadoop_3.3.1 -t public.ecr.aws/f1n8f8j1/livy-spark:0.8.0-incubating-spark_3.2.0_2.12-hadoop_3.3.1 .
      - docker push --all-tags public.ecr.aws/f1n8f8j1/livy-spark
      - cd ../..
      - cd livy/0.8.0-incubating-spark_3.2.0_2.12-hadoop_3.3.1
      - docker build -t public.ecr.aws/f1n8f8j1/livy:0.8.0-incubating-spark_3.2.0_2.12-hadoop_3.3.1 .
      - docker push --all-tags public.ecr.aws/f1n8f8j1/livy
      - cd ../..
      - cd jupyter/4.6.3-sparkmagic_0.15.0
      - docker build -t public.ecr.aws/f1n8f8j1/jupyter:4.6.3-sparkmagic_0.15.0 .
      - docker push --all-tags public.ecr.aws/f1n8f8j1/jupyter
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
